# Generated by Django 4.2.23 on 2025-07-23 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'ordering': ['-created_at'], 'permissions': [('can_manage_inquiries', 'Can view and respond to inquiries')]},
        ),
    ]
