# Generated by Django 4.2.23 on 2025-07-23 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_allergen_name_alter_historicalallergen_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergen',
            options={'permissions': [('can_manage_menu', 'Can add and edit menu items')]},
        ),
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ('order',), 'permissions': [('can_manage_menu', 'Can add and edit menu items')]},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'permissions': [('can_manage_menu', 'Can add and edit menu items')]},
        ),
        migrations.AlterModelOptions(
            name='menutype',
            options={'permissions': [('can_manage_menu', 'Can add and edit menu items')]},
        ),
    ]
