# Generated by Django 4.2.23 on 2025-07-21 14:11

import bookings.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_status_alter_historicalbooking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(validators=[bookings.validators.validate_booking_hour]),
        ),
        migrations.AlterField(
            model_name='historicalbooking',
            name='time',
            field=models.TimeField(validators=[bookings.validators.validate_booking_hour]),
        ),
    ]
