# Generated by Django 4.2.23 on 2025-07-21 14:35

import bookings.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_time_alter_historicalbooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(validators=[bookings.validators.validate_future_date]),
        ),
        migrations.AlterField(
            model_name='historicalbooking',
            name='date',
            field=models.DateField(validators=[bookings.validators.validate_future_date]),
        ),
    ]
