# Generated by Django 4.2.23 on 2025-07-22 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_date_alter_historicalbooking_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-date', '-time'], 'permissions': [('can_manage_bookings', 'Can confirm or reject bookings')]},
        ),
    ]
